#!/bin/bash

if [[ "$DOCKER_TAG" =~ "test-" ]]; then

	VERSION=$( echo $DOCKER_TAG | cut -d'-' -f2 )
	
	if [ "$VERSION" == "latest" ] || [ "$VERSION" == "7.1" ]; then
		TAG="latest"
	elif [ "$VERSION" == "6.1" ]; then
		TAG="6.1.0.1-196"
	else
		exit -1
	fi

	SCRIPT_DIR=$( cd "$( dirname "$0" )" && pwd )
	cp $SCRIPT_DIR/Dockerfile-test $SCRIPT_DIR/Dockerfile-test-tmp
	sed -i '' "s#@TAG@#$TAG#" $SCRIPT_DIR/Dockerfile-test-tmp

	docker build -f Dockerfile-test-tmp -t $IMAGE_NAME .

elif [ "$DOCKER_TAG" == "latest" ]; then

	docker build \
	--build-arg GIT_BRANCH="$SOURCE_BRANCH" \
	--build-arg GIT_COMMIT="$GIT_SHA1" \
	--build-arg GIT_MESSAGE="$GIT_MSG" \
	-t $IMAGE_NAME .

else

	PDI_RELEASE=$DOCKER_TAG
	PDI_VERSION=$( echo $PDI_RELEASE | cut -d'.' -f1,2 )
	
	docker build \
	--build-arg PDI_VERSION=$PDI_VERSION \
	--build-arg PDI_RELEASE=$PDI_RELEASE \
	--build-arg GIT_BRANCH="$SOURCE_BRANCH" \
	--build-arg GIT_COMMIT="$GIT_SHA1" \
	--build-arg GIT_MESSAGE="$GIT_MSG" \
	-t $IMAGE_NAME .

fi